project:
  type: website

website:
  title: "hw3b-vijithaviswanathan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

project:
  type: website
  output-dir: docs 